
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author alumno
 */
public class NewJFrame extends javax.swing.JFrame {

    Graphics2D g2d;
    Color color = Color.BLACK;
    BufferedImage bufferedImage;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        bufferedImage = new BufferedImage(jPanelLienzo.getWidth(), jPanelLienzo.getHeight(), BufferedImage.TYPE_INT_ARGB);
        g2d = (Graphics2D) bufferedImage.getGraphics();
        jLabelLienzo.setIcon(new ImageIcon(bufferedImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEnvio = new javax.swing.JTextField();
        jTextFieldDni = new javax.swing.JTextField();
        jPanelLienzo = new javax.swing.JPanel();
        jLabelLienzo = new javax.swing.JLabel();
        jSlider = new javax.swing.JSlider();
        jButtonSave = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabelSizePen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nº Envío:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("DNI:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        jPanel1.add(jTextFieldEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 132, -1));
        jPanel1.add(jTextFieldDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 132, -1));

        jPanelLienzo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLienzo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelLienzo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pintar(evt);
            }
        });

        javax.swing.GroupLayout jPanelLienzoLayout = new javax.swing.GroupLayout(jPanelLienzo);
        jPanelLienzo.setLayout(jPanelLienzoLayout);
        jPanelLienzoLayout.setHorizontalGroup(
            jPanelLienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLienzoLayout.createSequentialGroup()
                .addComponent(jLabelLienzo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanelLienzoLayout.setVerticalGroup(
            jPanelLienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelLienzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 113, 280, 120));

        jSlider.setMajorTickSpacing(10);
        jSlider.setMaximum(80);
        jSlider.setMinimum(5);
        jSlider.setValue(20);
        jSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderStateChanged(evt);
            }
        });
        jPanel1.add(jSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jButtonSave.setText("ENVIAR");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jButtonClear.setText("CLEAR");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));
        jPanel1.add(jLabelSizePen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 20, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pintar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pintar
        int x = evt.getX();
        int y = evt.getY();
        g2d.setColor(color);
        g2d.fillOval(x, y, jSlider.getValue(), jSlider.getValue());
        jLabelLienzo.updateUI();
    }//GEN-LAST:event_pintar

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {
            String envio = jTextFieldEnvio.getText();
            String dni = jTextFieldEnvio.getText();
            String ruta = dni + envio;
            ImageIO.write(bufferedImage, "png", new File(ruta + ".png"));
            JOptionPane.showMessageDialog(this, "Firma guardada", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            if (g2d != null && bufferedImage != null) {
                g2d.setComposite(java.awt.AlphaComposite.Clear);
                g2d.fillRect(0, 0, bufferedImage.getWidth(), bufferedImage.getHeight());
                g2d.setComposite(java.awt.AlphaComposite.SrcOver);
                jLabelLienzo.repaint();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        if (g2d != null && bufferedImage != null) {
            g2d.setComposite(java.awt.AlphaComposite.Clear);
            g2d.fillRect(0, 0, bufferedImage.getWidth(), bufferedImage.getHeight());
            g2d.setComposite(java.awt.AlphaComposite.SrcOver);
            jLabelLienzo.repaint();
        }
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderStateChanged
        int valor = jSlider.getValue();
        jLabelSizePen.setText(String.valueOf(valor));
    }//GEN-LAST:event_jSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelLienzo;
    private javax.swing.JLabel jLabelSizePen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLienzo;
    private javax.swing.JSlider jSlider;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldEnvio;
    // End of variables declaration//GEN-END:variables
}
