/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author alumno
 */
public class NivelDos extends javax.swing.JDialog {

    NewJFrame padre;
    private long inicioTiempo;
    private javax.swing.Timer timer;
    private int segundosTranscurridos = 0;
    private long finTiempo;

    /**
     * Creates new form NivelDos
     */
    public NivelDos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        padre = (NewJFrame) parent;
        initComponents();
        inicioTiempo = System.currentTimeMillis();

        MiMouseListener mml = new MiMouseListener();
        muro1.addMouseListener(mml);
        muro2.addMouseListener(mml);
        muro3.addMouseListener(mml);
        muro4.addMouseListener(mml);
        muro5.addMouseListener(mml);
        muro6.addMouseListener(mml);
        muro7.addMouseListener(mml);
        muro8.addMouseListener(mml);
        muro9.addMouseListener(mml);
        muro10.addMouseListener(mml);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        muro1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        muro3 = new javax.swing.JButton();
        muro6 = new javax.swing.JButton();
        muro4 = new javax.swing.JButton();
        muro5 = new javax.swing.JButton();
        muro10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        muro7 = new javax.swing.JButton();
        muro8 = new javax.swing.JButton();
        muro2 = new javax.swing.JButton();
        muro9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(550, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("TIEMPO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        muro1.setBackground(new java.awt.Color(255, 51, 0));
        getContentPane().add(muro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 480, 20));

        jButton3.setText("INICIO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jButton4.setText("FIN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 80, -1));

        muro3.setBackground(new java.awt.Color(255, 0, 0));
        muro3.setText("jButton5");
        getContentPane().add(muro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 410, 80));

        muro6.setBackground(new java.awt.Color(255, 0, 0));
        muro6.setText("jButton6");
        getContentPane().add(muro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 130, 180));

        muro4.setBackground(new java.awt.Color(255, 0, 0));
        muro4.setText("jButton6");
        getContentPane().add(muro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 140, 190));

        muro5.setBackground(new java.awt.Color(255, 0, 0));
        muro5.setText("jButton6");
        getContentPane().add(muro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 190, 110));

        muro10.setBackground(new java.awt.Color(255, 0, 0));
        muro10.setText("jButton6");
        getContentPane().add(muro10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 190, 10));

        jLabel2.setText("NIVEL 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel3.setText("0000");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        muro7.setBackground(new java.awt.Color(255, 0, 0));
        muro7.setText("jButton6");
        getContentPane().add(muro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 150, 80));

        muro8.setBackground(new java.awt.Color(255, 0, 0));
        muro8.setText("jButton6");
        getContentPane().add(muro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 40, 80));

        muro2.setBackground(new java.awt.Color(255, 0, 0));
        muro2.setText("jButton6");
        getContentPane().add(muro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, 80));

        muro9.setBackground(new java.awt.Color(255, 0, 0));
        muro9.setText("jButton6");
        getContentPane().add(muro9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 50, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (timer != null && timer.isRunning()) {
            timer.stop();
        }

        // Calculamos el tiempo final
        long finTiempo = System.currentTimeMillis();
        long tiempoTotal = (finTiempo - inicioTiempo) / 1000; // segundos

        // Abrir el diálogo Ganaste
        Ganaste g = new Ganaste(padre, true, tiempoTotal, "Nivel 2");
        g.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Reiniciar contador
        segundosTranscurridos = 0;
        jLabel3.setText("Tiempo: 0s");

        // Registrar el momento de inicio
        inicioTiempo = System.currentTimeMillis();

        // Si ya había un timer anterior, lo paramos
        if (timer != null && timer.isRunning()) {
            timer.stop();
        }

        // Crear el temporizador que actualiza cada segundo
        timer = new javax.swing.Timer(1000, e -> {
            segundosTranscurridos++;
            jLabel3.setText("Tiempo: " + segundosTranscurridos + "s");
        });

        // Iniciar el temporizador
        timer.start();    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NivelDos dialog = new NivelDos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton muro1;
    private javax.swing.JButton muro10;
    private javax.swing.JButton muro2;
    private javax.swing.JButton muro3;
    private javax.swing.JButton muro4;
    private javax.swing.JButton muro5;
    private javax.swing.JButton muro6;
    private javax.swing.JButton muro7;
    private javax.swing.JButton muro8;
    private javax.swing.JButton muro9;
    // End of variables declaration//GEN-END:variables
}
