spring.application.name=ACADT_UT5_P1_E1
server.port=9000

# Excluir auto-configuración de DataSource (no se usa base de datos en estos ejercicios)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
