
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author alumno
 */
public class NewJFrame extends javax.swing.JFrame {

    Graphics2D g2d;
    Color color = Color.BLACK;
    BufferedImage bufferedImage;

    int x1, y1, x2, y2;
    boolean primerClick = true;
    String modo = "linea"; // o "cuadrado", "circulo", "hexagono"

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        bufferedImage = new BufferedImage(jPanel1.getWidth(), jPanel1.getHeight(), BufferedImage.TYPE_INT_ARGB);
        g2d = (Graphics2D) bufferedImage.getGraphics();
        jLabel1.setIcon(new ImageIcon(bufferedImage));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonColores = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jButtonCuadrado = new javax.swing.JButton();
        jButtonCirculo = new javax.swing.JButton();
        jButtonHexagono = new javax.swing.JButton();
        jButtonLinea = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pintar(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonColores.setText("Color picker");
        jButtonColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColoresActionPerformed(evt);
            }
        });

        jSlider1.setMaximum(40);
        jSlider1.setMinimum(1);
        jSlider1.setValue(20);

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonCuadrado.setText("cuadrado");
        jButtonCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuadradoActionPerformed(evt);
            }
        });

        jButtonCirculo.setText("circulo");
        jButtonCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCirculoActionPerformed(evt);
            }
        });

        jButtonHexagono.setText("hexágono");
        jButtonHexagono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHexagonoActionPerformed(evt);
            }
        });

        jButtonLinea.setText("linea");
        jButtonLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLineaActionPerformed(evt);
            }
        });

        jButton2.setText("libre");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonColores, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jButtonCuadrado)
                    .addComponent(jButtonCirculo)
                    .addComponent(jButtonHexagono)
                    .addComponent(jButtonLinea)
                    .addComponent(jButton2))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonColores)
                        .addGap(18, 18, 18)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCuadrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCirculo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHexagono)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLinea)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pintar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pintar
        if (modo.equals("libre")) {
            int x = evt.getX();
            int y = evt.getY();
            g2d.setColor(color);
            g2d.fillOval(x, y, jSlider1.getValue(), jSlider1.getValue());
            jLabel1.updateUI();
        }

    }//GEN-LAST:event_pintar

    private void dibujarFigura(java.awt.event.MouseEvent evt) {
        if (primerClick) {
            x1 = evt.getX();
            y1 = evt.getY();
            primerClick = false;
        } else {
            int x2 = evt.getX();
            int y2 = evt.getY();
            primerClick = true;

            g2d.setColor(color);
            g2d.setStroke(new BasicStroke(3));

            int ancho = Math.abs(x2 - x1);
            int alto = Math.abs(y2 - y1);
            int x = Math.min(x1, x2);
            int y = Math.min(y1, y2);

            switch (modo) {
                case "cuadrado":
                    g2d.drawRect(x, y, ancho, alto);
                    break;
                case "circulo":
                    int diametro = Math.max(ancho, alto);
                    g2d.drawOval(x, y, diametro, diametro);
                    break;
                case "hexagono":
                    int r = Math.max(ancho, alto) / 2;
                    int cx = (x1 + x2) / 2;
                    int cy = (y1 + y2) / 2;
                    int[] xs = new int[6];
                    int[] ys = new int[6];
                    for (int i = 0; i < 6; i++) {
                        xs[i] = cx + (int) (r * Math.cos(i * Math.PI / 3));
                        ys[i] = cy + (int) (r * Math.sin(i * Math.PI / 3));
                    }
                    g2d.drawPolygon(xs, ys, 6);
                    break;
                case "linea":
                    g2d.drawLine(x1, y1, x2, y2);
                    break;
            }

            jLabel1.updateUI();
        }
    }


    private void jButtonColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColoresActionPerformed
        jColorChooser = new JColorChooser();
        color = JColorChooser.showDialog(null, "Seleccione un color", color);
    }//GEN-LAST:event_jButtonColoresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String ruta = JOptionPane.showInputDialog("Escribe el nombre del archivo");
            ImageIO.write(bufferedImage, "png", new File(ruta + ".png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuadradoActionPerformed
        modo = "cuadrado";
    }//GEN-LAST:event_jButtonCuadradoActionPerformed

    private void jButtonCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCirculoActionPerformed
        modo = "circulo";
    }//GEN-LAST:event_jButtonCirculoActionPerformed

    private void jButtonHexagonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHexagonoActionPerformed
        modo = "hexagono";
    }//GEN-LAST:event_jButtonHexagonoActionPerformed

    private void jButtonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLineaActionPerformed
        modo = "linea";
    }//GEN-LAST:event_jButtonLineaActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if (!modo.equals("libre")) {
            dibujarFigura(evt);
        }    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modo = "libre";
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCirculo;
    private javax.swing.JButton jButtonColores;
    private javax.swing.JButton jButtonCuadrado;
    private javax.swing.JButton jButtonHexagono;
    private javax.swing.JButton jButtonLinea;
    private javax.swing.JColorChooser jColorChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
