CREATE DATABASE REPASO;
USE REPASO;

CREATE TABLE PRODUCTOS (
    ID INT PRIMARY KEY,
    DESCRIPCION VARCHAR(50) NOT NULL,
    STOCKACTUAL INT,
    STOCKMINIMO INT,
    PVP DECIMAL(10,2)
);

CREATE TABLE CLIENTES (
    ID INT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(50),
    POBLACION VARCHAR(50),
    TELEF VARCHAR(20),
    NIF VARCHAR(10)
);

CREATE TABLE VENTAS (
    IDVENTA INT PRIMARY KEY,
    FECHAVENTA DATE NOT NULL,
    IDCLIENTE INT,
    IDPRODUCTO INT,
    CANTIDAD INT,
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES(ID),
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(ID)
);

select * from productos;
