
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author daniel
 */
public class NewJFrame extends javax.swing.JFrame {

    Graphics2D g2d;
    Color color = Color.BLACK;
    BufferedImage bufferedImage;
    int x1, y1, x2, y2;
    boolean primerClick = true;
    String modo = "free";

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jTextAreaDocument.setPreferredSize(jTextAreaDocument.getSize());
        jScrollPane1.setPreferredSize(jScrollPane1.getSize());
        bufferedImage = new BufferedImage(jPanelLienzo.getWidth(), jPanelLienzo.getHeight(), BufferedImage.TYPE_INT_ARGB);
        g2d = (Graphics2D) bufferedImage.getGraphics();
        jLabelLienzo.setIcon(new ImageIcon(bufferedImage));
        configurarModos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupShapes = new javax.swing.ButtonGroup();
        jPanelLienzo = new javax.swing.JPanel();
        jLabelLienzo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDocument = new javax.swing.JTextArea();
        jSliderPenSize = new javax.swing.JSlider();
        jButtonColorChooser = new javax.swing.JButton();
        jLabelPenSize = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonSquare = new javax.swing.JRadioButton();
        jRadioButtonCircle = new javax.swing.JRadioButton();
        jRadioButtonHex = new javax.swing.JRadioButton();
        jRadioButtonLine = new javax.swing.JRadioButton();
        jRadioButtonFree = new javax.swing.JRadioButton();
        jSliderFontSize = new javax.swing.JSlider();
        jLabelFontSize = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuOpen = new javax.swing.JMenu();
        jMenuItemOpenCanvas = new javax.swing.JMenuItem();
        jMenuItemOpenDocument = new javax.swing.JMenuItem();
        jMenuSave = new javax.swing.JMenu();
        jMenuItemSaveCanvas = new javax.swing.JMenuItem();
        jMenuItemSaveDocument = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemClearCanvas = new javax.swing.JMenuItem();
        jMenuItemClearDocument = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLienzo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLienzo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabelLienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelLienzoMouseDragged(evt);
            }
        });
        jLabelLienzo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelLienzoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelLienzoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelLienzoLayout = new javax.swing.GroupLayout(jPanelLienzo);
        jPanelLienzo.setLayout(jPanelLienzoLayout);
        jPanelLienzoLayout.setHorizontalGroup(
            jPanelLienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLienzo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );
        jPanelLienzoLayout.setVerticalGroup(
            jPanelLienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextAreaDocument.setColumns(20);
        jTextAreaDocument.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDocument);

        jSliderPenSize.setValue(20);

        jButtonColorChooser.setText("Palette");
        jButtonColorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorChooserActionPerformed(evt);
            }
        });

        buttonGroupShapes.add(jRadioButtonSquare);
        jRadioButtonSquare.setText("Square");

        buttonGroupShapes.add(jRadioButtonCircle);
        jRadioButtonCircle.setText("Circle");

        buttonGroupShapes.add(jRadioButtonHex);
        jRadioButtonHex.setText("Hexagon");

        buttonGroupShapes.add(jRadioButtonLine);
        jRadioButtonLine.setText("Line");

        buttonGroupShapes.add(jRadioButtonFree);
        jRadioButtonFree.setText("Free");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jRadioButtonSquare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCircle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonHex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonFree)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButtonSquare)
                .addComponent(jRadioButtonCircle)
                .addComponent(jRadioButtonHex)
                .addComponent(jRadioButtonLine)
                .addComponent(jRadioButtonFree))
        );

        jSliderFontSize.setMaximum(33);
        jSliderFontSize.setMinimum(10);
        jSliderFontSize.setValue(12);
        jSliderFontSize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderFontSizeStateChanged(evt);
            }
        });

        jLabelFontSize.setText("12");

        jMenuFile.setText("File");

        jMenuOpen.setText("Open");

        jMenuItemOpenCanvas.setText("Canvas");
        jMenuItemOpenCanvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenCanvasActionPerformed(evt);
            }
        });
        jMenuOpen.add(jMenuItemOpenCanvas);

        jMenuItemOpenDocument.setText("Document");
        jMenuItemOpenDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenDocumentActionPerformed(evt);
            }
        });
        jMenuOpen.add(jMenuItemOpenDocument);

        jMenuFile.add(jMenuOpen);

        jMenuSave.setText("Save");

        jMenuItemSaveCanvas.setText("Canvas");
        jMenuItemSaveCanvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveCanvasActionPerformed(evt);
            }
        });
        jMenuSave.add(jMenuItemSaveCanvas);

        jMenuItemSaveDocument.setText("Document");
        jMenuItemSaveDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveDocumentActionPerformed(evt);
            }
        });
        jMenuSave.add(jMenuItemSaveDocument);

        jMenuFile.add(jMenuSave);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuItemClearCanvas.setText("Clear canvas");
        jMenuItemClearCanvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClearCanvasActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemClearCanvas);

        jMenuItemClearDocument.setText("Clear text");
        jMenuItemClearDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClearDocumentActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemClearDocument);

        jMenuBar1.add(jMenuEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonColorChooser)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelLienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSliderPenSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelPenSize, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSliderFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonColorChooser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderPenSize, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSliderFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelPenSize, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemClearCanvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClearCanvasActionPerformed
        if (g2d != null && bufferedImage != null) {
            Graphics2D g2 = (Graphics2D) bufferedImage.getGraphics();
            g2.setColor(Color.WHITE);
            g2.fillRect(0, 0, bufferedImage.getWidth(), bufferedImage.getHeight());
            g2.dispose();
            jLabelLienzo.repaint();
        }
    }//GEN-LAST:event_jMenuItemClearCanvasActionPerformed

    private void jMenuItemOpenDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenDocumentActionPerformed
        JFileChooser chooser = new JFileChooser();
        int resultado = chooser.showOpenDialog(null);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = chooser.getSelectedFile();
            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                jTextAreaDocument.setText("");
                String linea;
                while ((linea = br.readLine()) != null) {
                    jTextAreaDocument.append(linea + "\n");
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al abrir archivo");
            }
        }    }//GEN-LAST:event_jMenuItemOpenDocumentActionPerformed

    private void jMenuItemSaveDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveDocumentActionPerformed
        JFileChooser chooser = new JFileChooser();
        int resultado = chooser.showSaveDialog(null);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = chooser.getSelectedFile();
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(archivo))) {
                bw.write(jTextAreaDocument.getText());
                JOptionPane.showMessageDialog(null, "Documento guardado correctamente");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al guardar archivo");
            }
        }    }//GEN-LAST:event_jMenuItemSaveDocumentActionPerformed

    private void jLabelLienzoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLienzoMouseDragged
        if (modo.equals("free")) {
            int x = evt.getX();
            int y = evt.getY();
            g2d.setColor(color);
            g2d.fillOval(x, y, jSliderPenSize.getValue(), jSliderPenSize.getValue());
            jLabelPenSize.setText(String.valueOf(jSliderPenSize.getValue()));
            jLabelLienzo.repaint();
        }
    }//GEN-LAST:event_jLabelLienzoMouseDragged

    private void jMenuItemSaveCanvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveCanvasActionPerformed
        try {
            String ruta = JOptionPane.showInputDialog("Escribe el nombre del archivo");
            ImageIO.write(bufferedImage, "png", new File(ruta + ".png"));
        } catch (IOException e) {
            e.printStackTrace();
        }    }//GEN-LAST:event_jMenuItemSaveCanvasActionPerformed

    private void jMenuItemOpenCanvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenCanvasActionPerformed
        JFileChooser chooser = new JFileChooser();
        int resultado = chooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = chooser.getSelectedFile();
            try {
                BufferedImage img = ImageIO.read(archivo);
                bufferedImage = new BufferedImage(
                        jPanelLienzo.getWidth(),
                        jPanelLienzo.getHeight(),
                        BufferedImage.TYPE_INT_ARGB
                );

                g2d = bufferedImage.createGraphics();
                g2d.drawImage(img, 0, 0, jPanelLienzo.getWidth(), jPanelLienzo.getHeight(), null);

                jLabelLienzo.setIcon(new ImageIcon(bufferedImage));
                jLabelLienzo.repaint();

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al abrir la imagen");
            }
        }
    }//GEN-LAST:event_jMenuItemOpenCanvasActionPerformed

    private void jButtonColorChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorChooserActionPerformed
        color = JColorChooser.showDialog(null, "Seleccione un color", color);
    }//GEN-LAST:event_jButtonColorChooserActionPerformed

    private void jLabelLienzoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLienzoMousePressed
        if (!modo.equals("free")) {
            dibujarFigura(evt);
        }
    }//GEN-LAST:event_jLabelLienzoMousePressed

    private void jLabelLienzoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLienzoMouseReleased
        if (!modo.equals("free")) {
            dibujarFigura(evt);
        }
    }//GEN-LAST:event_jLabelLienzoMouseReleased

    private void jSliderFontSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderFontSizeStateChanged
        int tamano = jSliderFontSize.getValue();
        jTextAreaDocument.setFont(new Font("Arial", Font.PLAIN, tamano));
        jLabelFontSize.setText(String.valueOf(tamano));
    }//GEN-LAST:event_jSliderFontSizeStateChanged

    private void jMenuItemClearDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClearDocumentActionPerformed
        jTextAreaDocument.setText("");
    }//GEN-LAST:event_jMenuItemClearDocumentActionPerformed

    private void dibujarFigura(java.awt.event.MouseEvent evt) {
        if (primerClick) {
            x1 = evt.getX();
            y1 = evt.getY();
            primerClick = false;
        } else {
            int x2 = evt.getX();
            int y2 = evt.getY();
            primerClick = true;

            g2d.setColor(color);
            g2d.setStroke(new BasicStroke(3));

            int ancho = Math.abs(x2 - x1);
            int alto = Math.abs(y2 - y1);
            int x = Math.min(x1, x2);
            int y = Math.min(y1, y2);

            switch (modo) {
                case "square":
                    g2d.drawRect(x, y, ancho, alto);
                    break;
                case "circle":
                    int diametro = Math.max(ancho, alto);
                    g2d.drawOval(x, y, diametro, diametro);
                    break;
                case "hexagon":
                    int r = Math.max(ancho, alto) / 2;
                    int cx = (x1 + x2) / 2;
                    int cy = (y1 + y2) / 2;
                    int[] xs = new int[6];
                    int[] ys = new int[6];
                    for (int i = 0; i < 6; i++) {
                        xs[i] = cx + (int) (r * Math.cos(i * Math.PI / 3));
                        ys[i] = cy + (int) (r * Math.sin(i * Math.PI / 3));
                    }
                    g2d.drawPolygon(xs, ys, 6);
                    break;
                case "line":
                    g2d.drawLine(x1, y1, x2, y2);
                    break;
            }

            jLabelLienzo.repaint();

        }
    }

    private void configurarModos() {
        jRadioButtonFree.addActionListener(e -> modo = "free");
        jRadioButtonSquare.addActionListener(e -> modo = "square");
        jRadioButtonCircle.addActionListener(e -> modo = "circle");
        jRadioButtonHex.addActionListener(e -> modo = "hexagon");
        jRadioButtonLine.addActionListener(e -> modo = "line");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupShapes;
    private javax.swing.JButton jButtonColorChooser;
    private javax.swing.JLabel jLabelFontSize;
    private javax.swing.JLabel jLabelLienzo;
    private javax.swing.JLabel jLabelPenSize;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemClearCanvas;
    private javax.swing.JMenuItem jMenuItemClearDocument;
    private javax.swing.JMenuItem jMenuItemOpenCanvas;
    private javax.swing.JMenuItem jMenuItemOpenDocument;
    private javax.swing.JMenuItem jMenuItemSaveCanvas;
    private javax.swing.JMenuItem jMenuItemSaveDocument;
    private javax.swing.JMenu jMenuOpen;
    private javax.swing.JMenu jMenuSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLienzo;
    private javax.swing.JRadioButton jRadioButtonCircle;
    private javax.swing.JRadioButton jRadioButtonFree;
    private javax.swing.JRadioButton jRadioButtonHex;
    private javax.swing.JRadioButton jRadioButtonLine;
    private javax.swing.JRadioButton jRadioButtonSquare;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSliderFontSize;
    private javax.swing.JSlider jSliderPenSize;
    private javax.swing.JTextArea jTextAreaDocument;
    // End of variables declaration//GEN-END:variables
}
